#
# About: Dockerfile for containerized DPDK
#

FROM ubuntu:16.04

ENV RTE_SDK=/root/dpdk
ENV RTE_TARGET=x86_64-native-linuxapp-gcc

RUN apt-get update && apt-get install -y net-tools \
    build-essential automake python-pip libcap-ng-dev gawk pciutils kmod \
    linux-headers-$(uname -a | awk '{print $3}') \
    git hugepages clang doxygen \
    libnuma-dev libpcap-dev

WORKDIR /root
COPY ./build_dpdk_base.sh /root
RUN /root/build_dpdk_base.sh stable

CMD ["/usr/bin/bash"]
