#
# Dockerfile for MoonGen traffic generator
#

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y git build-essential cmake linux-headers-`uname -r` pciutils libnuma-dev

WORKDIR /root

RUN \
    git clone https://github.com/emmericp/MoonGen && \
    cd MoonGen && \
    ./build.sh

CMD ["bash"]
