#
# Dockerfile for OpenDataPlane (ODP)
#

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y build-essential cmake linux-headers-`uname -r` pciutils libnuma-dev
RUN apt-get install -y git

WORKDIR /root

CMD ["bash"]
