# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS := af_xdp_dpdk_kern
USER_TARGETS := af_xdp_dpdk_user

LIB_OBJS += ../common/ext_xdp_user_utils.o

LIB_DIR = /opt/xdp-tools/lib
include $(LIB_DIR)/common.mk
